FROM ubuntu

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN python3 -m pip install Django
RUN pip3 install redis

WORKDIR /usr/share/djangoProject/

EXPOSE 8000

COPY . .

CMD [ "python3", "learnDcompose/manage.py", "runserver", "0.0.0.0:8000" ]